# A sample Gemfile
source 'https://rubygems.org'


gem 'ruby-debug-ide'
gem 'rack'
gem 'rack-protection'
gem 'mail'
gem 'rake'
gem 'unicorn'
gem 'haml-i18n'
gem 'mime-types'
gem 'activesupport'
gem 'json'
gem 'slim'
gem 'tilt'
gem 'hash-deep-merge'
gem 'rest-client'
gem 'twitter_oauth'
gem 'sass'
gem 'coffee-script'
gem 'juicer'
gem 'rspec'
gem 'cucumber'
gem 'capybara'
gem 'selenium-webdriver'
gem 'uglifier'
gem 'awesome_print'
gem 'debase'
gem 'opal', '>= 0.6.0'
gem 'opal-jquery'
gem 'simplecov'
gem 'compass'