# A sample Gemfile
source 'http://rubygems.org'

gem 'sprockets', '>=2.12.3'
gem 'tilt'
gem 'opal', '=0.6.3'
gem 'opal-jquery'
gem 'ruby-debug-ide'
gem 'rack'
gem 'rack-protection'
gem 'mail'
gem 'rake'
platforms :ruby do # linux
  gem 'unicorn'
end
gem 'haml-i18n'
gem 'mime-types'
gem 'activesupport'
gem 'json'
gem 'slim'
gem 'hash-deep-merge'
gem 'rest-client'
gem 'sass'
gem 'coffee-script'
gem 'juicer'
gem 'rspec'
gem 'cucumber'
gem 'capybara'
gem 'selenium-webdriver'
gem 'uglifier'
gem 'awesome_print'
gem 'debase'
gem 'simplecov'
gem 'compass'
gem 'memory_profiler'
gem 'therubyrhino'
gem 'minitest'
gem 'mocha'